version: '2'

services:
  web:
    build: web
    image: smithmicro/n7m-web:4.3
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
      - ui
    mem_limit: 100m
  ui:
    build: ui
    image: smithmicro/n7m-ui:3.4
    restart: always
    mem_limit: 100m
  app:
    build: app
    image: smithmicro/n7m-app:4.3
    #restart: always
    environment:
      - PGPASSWORD=n7m-geocoding
      - WEB_CONCURRENCY=2
    depends_on:
      - gis
    mem_limit: 200m
  feed:
    image: smithmicro/n7m-app:4.3
    depends_on:
      - gis
    environment:
      - PGPASSWORD=n7m-geocoding
      - OSM_FILENAME=monaco-latest.osm.pbf
      - NOMINATIM_REPLICATION_URL=https://download.geofabrik.de/europe/monaco-updates
      - NOMINATIM_REPLICATION_MAX_DIFF=3000
      - NOMINATIM_REPLICATION_UPDATE_INTERVAL=86400
    command: setup
    volumes:
      - ./data:/data/
  gis:
    build: gis
    image: smithmicro/n7m-gis:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=n7m-geocoding
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
